version: '3.8'

networks:
  bpw-bitcoin-node-network:
    external: true

services:
  electrs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bpw-electrs
    volumes:
      - ./bpw-electrs-data:/data
      - ./electrs.toml:/etc/electrs/config.toml
    ports:
      - "50001:50001"
    networks:
      - bpw-bitcoin-node-network
    command: ["electrs", "--conf", "/etc/electrs/config.toml"]
